badge/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from badges.views import BadgeList
from users import urls as user_urls
from badges import urls as badges_urls
from django.conf.urls.static import static
from django.conf import settings
from django_markdown import flatpages
flatpages.register()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'badge.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url('^markdown/', include('django_markdown.urls')),

    url(r'^users/', include(user_urls, namespace="users")),
    url(r'^pagini', include('django.contrib.flatpages.urls')),
)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += patterns('',
    url(r'^', include(badges_urls, namespace='badges')),
    url(r'^$', BadgeList.as_view(), name="index"),
)

badges/urls.py
from badges.views import BadgeList, BadgeViewSet, BadgeDetail, BadgeCreate, BadgeAppend, EvenimentViewSet, \
    EvenimentDetail, BadgeAproba, UpdateBadgeStatus, BadgeUpdateStatus
from django.conf.urls import patterns, include, url
from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'badges', BadgeViewSet)
router.register(r'evenimente', EvenimentViewSet)

urlpatterns = patterns('badges.views',
    url(r'api/1/badges/(?P<pk>\d+)/update/$', UpdateBadgeStatus.as_view(), name="badge_update"),
    url(r'api/1/', include(router.urls)),

    url(r'create/$', BadgeCreate.as_view(), name="badge_create"),
    url(r'append/(?P<pk>\d+)/$', BadgeAppend.as_view(), name="badge_append"),
    url(r'approve/(?P<pk>\d+)/$', BadgeUpdateStatus.as_view(), name="badge_aproba_status"),
    url(r'approve/$', BadgeAproba.as_view(), name="badge_aproba"),


    url(r'(?P<pk>\d+)/$', EvenimentDetail.as_view(), name="eveniment_detail"),
    url(r'colectie/$', BadgeList.as_view(), name="index"),
)

users/urls.py
from django.conf.urls import patterns, include, url
from django.core.urlresolvers import reverse_lazy
from users.forms import LoginForm

from users.views import Register, CurrentUserAPIView
from django.contrib.auth import views as auth_views

urlpatterns = patterns('users.views',
    url(r'login/$', auth_views.login, {'template_name': 'users/login.html', 'authentication_form': LoginForm}, name="login"),
    url(r'logout/$', auth_views.logout, {'next_page': reverse_lazy("badges:index")}, name="logout"),
    url(r'register/$', Register.as_view(), name="register"),
    url(r'api/1/utilizatori/get_current/$', CurrentUserAPIView.as_view(), name="current_user")
)

templates/base.html
{% load staticfiles %}
{% load gravatar %}
<!DOCTYPE html>
<html lang="en" ng-app="badges">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Badge Project by UP17">
    <meta name="author" content="yeti">
{#    <link rel="icon" href="../../favicon.ico">#}

    <title>Badge-uri cercetasesti</title>
    {% block meta %}
        <meta property="og:title" content="Colecția de badge-uri și amintiri" />
        <meta property="og:type" content="object" />
        <meta property="og:image" content="{{ URL_ROOT }}{% static 'img/project_fb_cover.png' %}">
        <meta property="og:url" content="{{ URL_ROOT }}" />
        <meta property="og:description" content="Un proiect al UP17 pentru călătoria înapoi în timp :)" />
    {% endblock %}
    <!-- Bootstrap core CSS -->
    <link href="{% static 'bootstrap/dist/css/bootstrap.min.css'%}" rel="stylesheet">
    <link href="{% static 'fontawesome/css/font-awesome.css' %}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'css/badge_layout.css' %}" rel="stylesheet">
    <link href="{% static 'css/badge_up17.css' %}" rel="stylesheet">

    <link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  <style>
      .footer {
          background-image: url("{% static "img/footer_up17.png" %}");
      }
  </style>
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/" style="background-image: url('{% static 'img/project_up_brand.png' %}')">Dăm timpul înapoi</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url "badges:index" %}">Colecție</a></li>
            <li><a href="{% url "django.contrib.flatpages.views.flatpage" url="/despre/" %}">Despre proiect</a></li>
            {% if user.is_authenticated and user.is_staff %}
                <li><a href = "{% url "badges:badge_aproba" %}">Aprobare</a></li>
            {% endif %}
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% if not user.is_authenticated %}
              <li><a href="{% url "users:login" %}">Login</a></li>
            {% else %}
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><img class = "gravatar-profile" src = "{% gravatar_url user.username    20 %}"> {{ user }} <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="{% url "users:logout" %}">Logout</a></li>
                <li class = "disabled"><a href="#">Profil</a></li>
                <li class = "disabled"><a href="#">Schimbă parola</a></li>
                <li class="divider"></li>
                <li><a href="#">-</a></li>
              </ul>
            </li>
            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>


    <div class="container">
        <div class="page-header">
            <h1>{% block page_title %}{% endblock %}</h1>
        </div>

        <div id="message_container" style="margin-bottom: 30px">
            {% if messages %}
                {% for message in messages %}
                    <div id="msg_{{ forloop.count }}" {% if message.tags %}
                         class="django-message alert alert-{{ message.tags }}"{% endif %}>
                        {{ message }}
                        <a class="close" data-dismiss="alert" href="#">&times;</a>
                    </div>
                {% endfor %}
            {% endif %}
            <script type="text/javascript">
                function hide_messages() {
                    jQuery(".django-message").hide("fast");
                }
                setTimeout("hide_messages()", 1000 * 3);
            </script>
        </div>

      {% block content %}
      {% endblock %}
    </div><!-- /.container -->
    <footer class="footer">
      <div class="container">
        <p class="text-muted" style = "margin-top: 10px; text-align: center"><img src = "{% static "img/oncr.png" %}"><br>Cercetașii României Alba Iulia</p>
      </div>
    </footer>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <script src="{% static "lodash/dist/lodash.js" %}"></script>
    <script src="{% static "moment/moment.js" %}"></script>
    <script src="{% static "moment/locale/ro.js" %}"></script>
    <script src="{% static "angular/angular.js" %}"></script>
    <script src="{% static "angular-resource/angular-resource.js" %}"></script>
    <script src="{% static "angular-moment/angular-moment.js" %}"></script>

    <script src = "{% static 'jquery-bridget/jquery.bridget.js' %}"></script>
    <script src = "{% static 'get-style-property/get-style-property.js' %}"></script>
    <script src = "{% static 'get-size/get-size.js' %}"></script>
    <script src = "{% static 'eventEmitter/EventEmitter.js' %}"></script>
    <script src = "{% static 'eventie/eventie.js' %}"></script>
    <script src = "{% static 'doc-ready/doc-ready.js' %}"></script>
    <script src = "{% static 'matches-selector/matches-selector.js' %}"></script>
    <script src = "{% static 'outlayer/item.js' %}"></script>
    <script src = "{% static 'outlayer/outlayer.js' %}"></script>
    <script src = "{% static 'masonry/masonry.js' %}"></script>
    <script src = "{% static 'imagesloaded/imagesloaded.js' %}"></script>
    <script src = "{% static 'angular-masonry/angular-masonry.js' %}"></script>
    <script src = "{% static 'ngInfiniteScroll/build/ng-infinite-scroll.js' %}"></script>

    {% block extrajs %}
    {% endblock %}

    <script src="{% static "js/app.js" %}"></script>

    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-23160397-3', 'auto');
      ga('send', 'pageview');

    </script>
  </body>
</html>