badge/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from badges.views import BadgeList
from users import urls as user_urls
from badges import urls as badges_urls
from django.conf.urls.static import static
from django.conf import settings
from django_markdown import flatpages
flatpages.register()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'badge.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url('^markdown/', include('django_markdown.urls')),

    url(r'^users/', include(user_urls, namespace="users")),
    url(r'^pagini', include('django.contrib.flatpages.urls')),
)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += patterns('',
    url(r'^', include(badges_urls, namespace='badges')),
    url(r'^$', BadgeList.as_view(), name="index"),
)

badges/urls.py
from badges.views import BadgeList, BadgeViewSet, BadgeDetail, BadgeCreate, BadgeAppend, EvenimentViewSet, \
    EvenimentDetail, BadgeAproba, UpdateBadgeStatus, BadgeUpdateStatus
from django.conf.urls import patterns, include, url
from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'badges', BadgeViewSet)
router.register(r'evenimente', EvenimentViewSet)

urlpatterns = patterns('badges.views',
    url(r'api/1/badges/(?P<pk>\d+)/update/$', UpdateBadgeStatus.as_view(), name="badge_update"),
    url(r'api/1/', include(router.urls)),

    url(r'create/$', BadgeCreate.as_view(), name="badge_create"),
    url(r'append/(?P<pk>\d+)/$', BadgeAppend.as_view(), name="badge_append"),
    url(r'approve/(?P<pk>\d+)/$', BadgeUpdateStatus.as_view(), name="badge_aproba_status"),
    url(r'approve/$', BadgeAproba.as_view(), name="badge_aproba"),


    url(r'(?P<pk>\d+)/$', EvenimentDetail.as_view(), name="eveniment_detail"),
    url(r'colectie/$', BadgeList.as_view(), name="index"),
)

badges/models.py
#coding: utf-8
import datetime
from django.contrib.auth.models import User
from django.contrib.sites.models import Site
from django.db import models
from imagekit.models.fields import ImageSpecField
from pilkit.processors.resize import ResizeToFill, SmartResize
import urllib

class Eveniment(models.Model):
    nume = models.CharField(max_length=255)
    an = models.IntegerField()

    class Meta:
        ordering = ["-an"]

    def __unicode__(self):
        return u"{0}, {1}".format(self.nume, self.an)

    @models.permalink
    def get_absolute_url(self):
        return ("badges:eveniment_detail", [], {"pk": self.id})

    def get_full_absolute_url(self):
        return "http://%s%s" % (Site.objects.get_current().domain, self.get_absolute_url())

    def facebook_share_link(self):
        base_url = "https://www.facebook.com/sharer/sharer.php?%s"
        return base_url % urllib.urlencode({"u": self.get_full_absolute_url()})

    def twitter_share_link(self):
        base_url = "https://twitter.com/share?%s"
        return base_url % urllib.urlencode({"url": self.get_full_absolute_url(), "text": self.__unicode__().encode("utf-8")})

    def get_badge_imagine_implicita(self):
        default = self.badgeuri_acceptate().filter(implicit_eveniment=True).first()
        if default is None:
            default = self.badgeuri_acceptate().filter(acceptat_status=2, imagine__isnull=False).first()
        if default is None:
            return None

        if default.imagine:
            return default
        return None

    def imagine_mare(self):
        imagine = self.get_badge_imagine_implicita()
        return imagine.imagine_mare if imagine else None

    def imagine_thumbnail(self):
        imagine = self.get_badge_imagine_implicita()
        return imagine.imagine_thumbnail if imagine else None

    def imagine_mini(self):
        imagine = self.get_badge_imagine_implicita()
        return imagine.imagine_mini if imagine else None

    def posters(self):
        return self.badgeuri_acceptate().filter(poster__isnull=False).values_list("poster__id", flat=True)

    def badgeuri_acceptate(self):
        return self.badge_set.filter(acceptat_status=2)


BADGE_STATUSES = ((1, u"Indecis"), (2, u"Acceptat"), (3, u"Respins"))


class Badge(models.Model):
    poster = models.ForeignKey(User, null=True, blank=True)
    amintire = models.TextField(null=True, blank=True, verbose_name=u"Povestea badge-ului", help_text=u"Adică cum și de ce a ajuns la tine, ce amintiri ai din campul sau din acțiunea aia, cu cine erai acolo?")

    timestamp = models.DateTimeField(auto_now_add=True)
    acceptat_status = models.IntegerField(default=1, choices=BADGE_STATUSES)
    acceptat_pe = models.DateTimeField(null=True, blank=True)
    acceptat_de = models.ForeignKey(User, null=True, blank=True, related_name="badgeuri_acceptate")

    eveniment = models.ForeignKey("badges.Eveniment")
    implicit_eveniment = models.BooleanField(default=False)

    imagine = models.ImageField(upload_to="badges", verbose_name=u"Super-poză cu badge-ul", help_text=u"O poză de calitate cu o dimensiune justificată :)", null=True, blank=True)
    imagine_thumbnail = ImageSpecField(source='imagine', processors=[SmartResize(300, 300, False)],
                                      format='JPEG', options={'quality': 95})
    imagine_mare = ImageSpecField(source='imagine', processors=[SmartResize(1200, 1200, False)],
                                      format='JPEG', options={'quality': 95})

    imagine_mini = ImageSpecField(source='imagine', processors=[SmartResize(50, 50, False)],
                                      format='JPEG', options={'quality': 95})



    class Meta:
        verbose_name = "Propunere badge"
        verbose_name_plural = "Propuneri badge"
        ordering = ["-timestamp"]

    def __unicode__(self):
        return u"{0}, {1}".format(self.eveniment.nume, self.eveniment.an)

    def marcheaza_acceptat(self, user, save=False):
        self.acceptat_status = 2
        self.acceptat_de = user
        self.acceptat_pe = datetime.datetime.now()
        if save:
            self.save()

badges/forms.py
#coding: utf-8
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Row, Div, Field, Submit
from django.core.exceptions import ValidationError
from django.forms.fields import CharField, IntegerField, ImageField
from django.forms.models import ModelForm
import datetime

from badges.models import Badge


__author__ = 'yeti'


class BadgeCreateForm(ModelForm):
    class Meta:
        model = Badge
        exclude = ("poster", "acceptat_status", "acceptat_pe", "acceptat_de", "eveniment")

    nume_activitate = CharField(max_length=255, label=u"De unde e badge-ul?", help_text=u"În ce camp sau în ce context l-ai dobândit?")
    an_activitate = IntegerField(max_value=int(datetime.date.today().strftime("%Y")), min_value=1990, label=u"Anul")

    imagine = ImageField(label=u"Super poză cu badge-ul", help_text=u"O poză de calitate cu o dimensiune justificată :)", required=True)

    def __init__(self, **kwargs):
        super(BadgeCreateForm, self).__init__(**kwargs)
        self.helper = FormHelper()

        self.helper.layout = Layout(Row(Div(Field("nume_activitate"), css_class="col-md-6 col-xs-12"),
                                        Div(Field("an_activitate"), css_class="col-md-2 col-xs-12"),
                                        Div(Field("imagine"), css_class="col-md-4 col-xs-12")),
                                    Row(Div(Field("amintire"), css_class="col-md-12 col-xs-12")))
        self.helper.add_input(Submit("submit", "Salvează", css_class="btn btn-success pull-right"))
        self.helper.form_action = "."
        self.helper.form_method = "post"
        self.helper.form_class = "form-horizontal"


class BadgeEventCreateForm(ModelForm):
    class Meta:
        model = Badge
        fields = ("amintire", "imagine")

    def __init__(self, **kwargs):
        super(BadgeEventCreateForm, self).__init__(**kwargs)
        self.helper = FormHelper()

        self.helper.layout = Layout(Row(Div(Field("amintire"), css_class="col-md-12 col-xs-12")),
                                    Row(Div(Field("imagine"), css_class="col-md-12 col-xs-12")))
        self.helper.add_input(Submit("submit", "Salvează", css_class="btn btn-success pull-right"))
        self.helper.form_action = "."
        self.helper.form_method = "post"
        self.helper.form_class = "form-horizontal"

badges/views.py
# coding: utf-8
from datetime import datetime
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test
from django.core.urlresolvers import reverse
from django.db.models.aggregates import Count
from django.http.response import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.utils.decorators import method_decorator
from django.views.generic.base import TemplateView, View
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.list import ListView
from rest_framework import viewsets
from rest_framework.generics import UpdateAPIView
from rest_framework.permissions import IsAuthenticated, IsAdminUser

from badges.models import Badge, Eveniment, BADGE_STATUSES
from badges.serializers import BadgeSerializer, EvenimentSerializer, PaginatedEvenimentSerializer, BadgeUpdateSerializer
from badges.forms import BadgeCreateForm, BadgeEventCreateForm


class BadgeList(TemplateView):
    template_name = "badges/badge_list.html"


class BadgeDetail(DetailView):
    template_name = "badges/eveniment_detail.html"
    model = Badge


class BadgeCreate(CreateView):
    template_name = "badges/badge_form.html"
    model = Badge
    form_class = BadgeCreateForm
    
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(BadgeCreate, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        self.object = form.save(commit=False)

        nume_eveniment = form.cleaned_data.get("nume_activitate")
        an_eveniment = form.cleaned_data.get("an_activitate")
        # import pdb; pdb.set_trace()
        eveniment, created = Eveniment.objects.get_or_create(nume=nume_eveniment, an=an_eveniment)
        self.object.eveniment = eveniment
        if created:
            self.object.implicit_eveniment = True

        self.object.poster = self.request.user
        if self.request.user.utilizator.is_auto_approved:
            self.object.marcheaza_acceptat(self.request.user, save=False)
            messages.success(self.request, u"Povestea ta a fost adăugată și apare acum în colecția de badge-uri!")
        else:
            messages.success(self.request, u"Povestea ta a fost salvată și va apărea în colecția de badge-uri după ce este verificată de cineva din echipa noastră!")
        return super(BadgeCreate, self).form_valid(form)

    def get_success_url(self):
        return reverse("badges:index")

    def get_context_data(self, **kwargs):
        data = super(BadgeCreate, self).get_context_data(**kwargs)
        data['titlu'] = u"Adaugă un badge și spune-i povestea"
        return data


class EvenimentDetail(DetailView):
    template_name = "badges/eveniment_detail.html"
    model = Eveniment


class BadgeAppend(CreateView):
    template_name = "badges/badge_form.html"
    model = Badge
    form_class = BadgeEventCreateForm

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        self.event = get_object_or_404(Eveniment, id=kwargs.pop("pk"))
        return super(BadgeAppend, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.eveniment = self.event
        self.object.save()
        self.object.poster = self.request.user
        if self.request.user.utilizator.is_auto_approved:
            self.object.marcheaza_acceptat(self.request.user, save=False)
            messages.success(self.request, u"Povestea ta a fost adăugată celorlalte! Mulțumim!")
        else:
            messages.success(self.request, u"Povestea ta a fost salvată și va apărea în colecția de badge-uri după ce este verificată de cineva din echipa noastră!")
        return super(BadgeAppend, self).form_valid(form)

    def get_success_url(self):
        return reverse("badges:index")

    def get_context_data(self, **kwargs):
        data = super(BadgeAppend, self).get_context_data(**kwargs)
        data['titlu'] = u"Povestea ta de la %s" % self.event
        return data


class BadgeAproba(ListView):
    model = Badge
    template_name = "badges/badge_approve_list.html"

    @method_decorator(user_passes_test(lambda u: u.is_staff))
    def dispatch(self, request, *args, **kwargs):
        self.status = int(request.GET.get("status", 1))
        if self.status not in [a[0] for a in BADGE_STATUSES]:
            self.status = 1
        return super(BadgeAproba, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        qs = super(BadgeAproba, self).get_queryset()
        qs = qs.filter(acceptat_status=self.status)
        return qs

    def get_context_data(self, **kwargs):
        data = super(BadgeAproba, self).get_context_data(**kwargs)
        data['statuses'] = BADGE_STATUSES
        data['current_status'] = self.status
        data['current_status_name'] = next((a[1] for a in BADGE_STATUSES if a[0] == self.status))
        return data


class BadgeUpdateStatus(View):
    @method_decorator(user_passes_test(lambda u: u.is_staff))
    def dispatch(self, request, *args, **kwargs):
        return super(BadgeUpdateStatus, self).dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.object = get_object_or_404(Badge, id=kwargs.pop("pk", 0))
        self.new_status = request.GET.get("status", 1)
        self.object.acceptat_status = self.new_status
        self.object.save()
        return HttpResponseRedirect(reverse("badges:badge_aproba") + "?status=1")




## API
class BadgeViewSet(viewsets.ModelViewSet):
    queryset = Badge.objects.filter(acceptat_status=2)
    serializer_class = BadgeSerializer


class EvenimentViewSet(viewsets.ModelViewSet):
    queryset = Eveniment.objects.filter(badge__acceptat_status=2).annotate(num_badges=Count('badge')).filter(num_badges__gte=0)
    serializer_class = EvenimentSerializer


class UpdateBadgeStatus(UpdateAPIView):
    model = Badge
    model_serializer_class = BadgeUpdateSerializer
    permission_classes = [IsAdminUser, ]

badges/templates/badges/badge_approve_list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load pagination_tags %}

{% block page_title %}
    Toate poveștile <small>{{ current_status_name }}e</small>
{% endblock %}

{% block content %}
    <div>
    <div class = "alert alert-info">Badge-uri în starea <strong>{{ current_status_name }}</strong>: {{ object_list.count }}.</div>
    <div class = 'pull-right btn-toolbar' style="margin-bottom: 40px">
        <div class = 'btn-group'>
            {% for status_id, status_name in statuses %}
                <a class = "btn-info btn btn-default {% if current_status == status_id %}disabled{% endif %}" href = "{% url "badges:badge_aproba" %}?status={{ status_id }}">{{ status_name }}</a>
            {% endfor %}
        </div>
    </div>
    <table class = "table table-striped">
        <thead>
            <tr>
                <th>#</th>
                <th>Eveniment</th>
                <th>Amintire</th>
                <th>Cine</th>
                <th class = "col-md-2">Când</th>
                <th>Poză</th>
                <th>Status</th>
                <th class = "col-md-1">&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            {% autopaginate object_list 20 %}
            {% for object in object_list %}
                <tr>
                    <td>#{{ object.id }}</td>
                    <td><a href = "{% url "badges:eveniment_detail" pk=object.eveniment.id %}">{{ object.eveniment }}</a></td>
                    <td>{{ object.amintire }}</td>
                    <td>{{ object.poster.utilizator }}</td>
                    <td>acum {{ object.timestamp|timesince }}</td>
                    <td>{% if object.imagine %}<span class = 'glyphicon glyphicon-ok'></span>{% endif %}</td>
                    <td>{{ object.get_acceptat_status_display }}</td>
                    <td>
                        <div class = 'btn-group pull-right'>
                            <a style = "color: green" href = "{% url "badges:badge_aproba_status" pk=object.id %}?status=2" data-new-status=2 class = "aproba-action btn btn-xs btn-default"><span class = "glyphicon glyphicon-thumbs-up"></span></a>
                            <a style = "color: red" href = "{% url "badges:badge_aproba_status" pk=object.id %}?status=3" data-new-status=3 class = "aproba-action btn btn-xs btn-default"><span class = "glyphicon glyphicon-thumbs-down"></span></a>
                        </div>
{#                        <a href = "#" ng-click="update_status({{ object.id }}, 2)">Aprobă</a> / <a href = "#" ng-click="update_status({{ object.id }}, 3)">Respinge</a></td>#}
                </tr>
            {% empty %}
                <tr>
                    <td>&nbsp;</td>
                    <td colspan="7"><em>Nu sunt povești în starea: <strong>{{ current_status_name }}</strong>.</em></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    {% paginate %}
    </div>
{% endblock %}

{% block extrajs %}
{#    <script>#}
{#        $("document").ready(function () {#}
{#            $(".aproba-action").click(function (e) {#}
{#                $.post($(this).attr("href"), {"status": $(this).data("new-status")}, function (data) {#}
{#                    #}
{#                })#}
{#                e.preventDefault()#}
{#            })#}
{#        })#}
{#    </script>#}
{% endblock %}

badges/templates/badges/badge_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block page_title %}
    {{ titlu }}
{% endblock %}

{% block content %}
    {% crispy form form.helper %}
{% endblock %}

badges/templates/badges/badge_list.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block page_title %}
    Colecția noastră de povești
{% endblock %}

{% block content %}
    <div ng-controller="BadgesController">
        <div class = "big-add-button"><a href = "{% url "badges:badge_create" %}"><span class = "glyphicon glyphicon-plus-sign"></span> <span class = "hidden-description">Adaugă și povestea ta</span></a></div>
        <div masonry item-selector=".badge-masonry-brick" infinite-scroll="load_more_badges()" infinite-scroll-distance="3">
            <div masonry-brick class="badge-masonry-brick col-md-3 col-xs-6" ng-repeat="event in evenimente">
                <a href = "/[[ event.id ]]/"><img ng-src="[[ event.imagine ]]" alt="[[ event.nume ]]"></a>
                <div class = "badge-toolbox">
                    <div class = "big-append-button" ng-show="!user_in_event(event)"><a href = "/append/[[ event.id ]]/"><span class = "glyphicon glyphicon-plus-sign"></span></a></div>
                    <div class = "already-checked" ng-show="user_in_event(event)"><span class = "glyphicon glyphicon-ok"></span></div>
{#                    <div><a href = "#"><span class = "glyphicon glyphicon-ok"></span></a></div>#}
                </div>
                <div class = "facebook"><a target="_blank" href ="[[ event.facebook_link ]]"><i class = "fa fa-facebook"></i></a></div>
                <div class = "twitter"><a target="_blank" href = "[[ event.twitter_link ]]"><i class = "fa fa-twitter"></i></a></div>
                <div class = "badge-contents">
                    <h2><a href = "/[[ event.id ]]/">[[ event.nume ]] [[ event.an ]]</a></h2>
                    <span style="font-size: 10px; color: #333;"><em am-time-ago="event.poveste.timestamp_processed" am-preprocess="unix"></em> de [[ event.poveste.poster.full_name ? event.poveste.poster.full_name : event.poveste.poster.username ]]</span><br>
                    <small>[[ event.poveste.amintire | limitTo: 300 ]] [[ event.poveste.amintire.length > 300 ? "..." : "" ]]</small>
                    <div class = "stats">[[ cercetasi_aici(event) ]]</div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

badges/templates/badges/eveniment_detail.html
{% extends 'base.html' %}
{% load gravatar %}
{% load staticfiles %}

{% block meta %}
    <meta property="og:title" content="{{ object }}" />
    <meta property="og:type" content="object" />
    <meta property="og:image" content="{{ URL_ROOT }}{% if object.imagine %}{{ object.imagine_mare.url }}{% else %}{% static 'img/project_fb_cover.png' %}{% endif %}">
    <meta property="og:url" content="{{ object.get_full_absolute_url }}" />
    <meta property="og:description" content="{{ object.get_badge_imagine_implicita.amintire }}" />
{% endblock %}

{% block page_title %}
   {{ object }} {% if user.id not in object.posters %}<span style = "font-size: 14px" class = "pull-right">Ai și tu badge-ul acesta? <a style = "margin-left: 10px;" href = "{% url "badges:badge_append" pk=object.id %}" class = "btn btn-success">Spune-ne povestea ta!</a></span>{% endif %}
{% endblock %}

{% block content %}
    <div class = "row">
        <div class = "col-md-6 col-xs-12">
            <img style="width: 100%; text-align: left; margin-left: 0;" src = "{{ object.imagine_mare.url }}">
            <div class = "facebook"><a target="_blank" href ="{{ object.facebook_share_link }}"><i class = "fa fa-facebook"></i></a></div>
            <div class = "twitter"><a target="_blank" href = "{{ object.twitter_share_link }}"><i class = "fa fa-twitter"></i></a></div>
            {% if user.is_authenticated and user.is_staff %}
            <div class = "row" style="margin-top: 40px; ">
                <div class = "col-md-12">
                {% for badge in object.badgeuri_acceptate %}
                    {% if badge.imagine %}
                        <img src = "{{ badge.imagine_mini.url }}" style="padding: 5px; padding-left:0;">
                    {% endif %}
                {% endfor %}
                </div>
            </div>
            {% endif %}
        </div>
        <div class = "col-md-6 col-xs-12">
            {% for badge in object.badgeuri_acceptate %}
            <blockquote class = "{% if badge.poster == user %}amintire-proprie{% endif %}">
                {% with badge as amintire %}
                {{ amintire.amintire|linebreaks }}
                <small>{% with amintire.poster.utilizator as utilizator %}{% gravatar utilizator.user.email 16 %} {{ utilizator }}{% if utilizator.centru_local %}, {{ utilizator.centru_local }}{% endif %}, acum {{ amintire.timestamp|timesince }}{% endwith %}</small>
                {% endwith %}
            </blockquote>
            {% endfor %}
        </div>
    </div>
{% endblock %}